version: '3.4'

services:
  nginx:
    container_name: app_nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db

  db:
    container_name: pgsql
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: urlshortener
    ports:
      - 5432:5432
